version: "3"
services:
  db:
    container_name: officechief
    image: postgres:11.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: officechief_dev
      PGDATA: /var/lib/postgresql/data/11-5
networks:
  default:
    external:
      name: officechief_default
